[package]
name = "rsonist"
version = "0.1.0"
edition = "2024"
description = "A small, zero-dep JSON library"
license = "GPL3.0"
authors = ["Dallas S. <adsherman@tutamail.com>"]
repository = "https://github.com/dallas1295/rsonist"
categories = ["parser-implementations", "encoding", "json"]

[dependencies]

